//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure.MappingViews;

[assembly: DbMappingViewCacheTypeAttribute(
    typeof(PracticaNETRoP.Models.shoopbooksEntities),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySetsa90e6dc6a9ffe553b0da712ba4508200ff0516bafb99e9b12ffbfe5307b34b59))]

namespace Edm_EntityMappingGeneratedViews
{
    using System;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Core.Metadata.Edm;

    /// <summary>
    /// Implements a mapping view cache.
    /// </summary>
    [GeneratedCode("Entity Framework 6 Power Tools", "0.9.2.0")]
    internal sealed class ViewsForBaseEntitySetsa90e6dc6a9ffe553b0da712ba4508200ff0516bafb99e9b12ffbfe5307b34b59 : DbMappingViewCache
    {
        /// <summary>
        /// Gets a hash value computed over the mapping closure.
        /// </summary>
        public override string MappingHashValue
        {
            get { return "a90e6dc6a9ffe553b0da712ba4508200ff0516bafb99e9b12ffbfe5307b34b59"; }
        }

        /// <summary>
        /// Gets a view corresponding to the specified extent.
        /// </summary>
        /// <param name="extent">The extent.</param>
        /// <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        public override DbMappingView GetView(EntitySetBase extent)
        {
            if (extent == null)
            {
                throw new ArgumentNullException("extent");
            }

            var extentName = extent.EntityContainer.Name + "." + extent.Name;

            if (extentName == "VirtualShopModelStoreContainer.Invoices")
            {
                return GetView0();
            }

            if (extentName == "VirtualShopModelStoreContainer.Orders")
            {
                return GetView1();
            }

            if (extentName == "VirtualShopEntities.Invoices")
            {
                return GetView2();
            }

            if (extentName == "VirtualShopEntities.Orders")
            {
                return GetView3();
            }

            if (extentName == "VirtualShopModelStoreContainer.Products")
            {
                return GetView4();
            }

            if (extentName == "VirtualShopModelStoreContainer.Stock")
            {
                return GetView5();
            }

            if (extentName == "VirtualShopEntities.Products")
            {
                return GetView6();
            }

            if (extentName == "VirtualShopEntities.Stocks")
            {
                return GetView7();
            }

            return null;
        }

        /// <summary>
        /// Gets the view for VirtualShopModelStoreContainer.Invoices.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView0()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Invoices
        [VirtualShopModel.Store.Invoices](T1.Invoices_Id, T1.[Invoices.id_client], T1.Invoices_amount, T1.Invoices_dateInvoice, T1.Invoices_idOrder)
    FROM (
        SELECT 
            T.Id AS Invoices_Id, 
            T.id_client AS [Invoices.id_client], 
            T.amount AS Invoices_amount, 
            T.dateInvoice AS Invoices_dateInvoice, 
            T.idOrder AS Invoices_idOrder, 
            True AS _from0
        FROM VirtualShopEntities.Invoices AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for VirtualShopModelStoreContainer.Orders.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView1()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Orders
        [VirtualShopModel.Store.Orders](T1.Orders_Id, T1.Orders_units, T1.Orders_idClient, T1.Orders_idProduct)
    FROM (
        SELECT 
            T.Id AS Orders_Id, 
            T.units AS Orders_units, 
            T.idClient AS Orders_idClient, 
            T.ProductId AS Orders_idProduct, 
            True AS _from0
        FROM VirtualShopEntities.Orders AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for VirtualShopEntities.Invoices.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView2()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Invoices
        [VirtualShopModel.Invoice](T1.Invoice_Id, T1.[Invoice.id_client], T1.Invoice_amount, T1.Invoice_dateInvoice, T1.Invoice_idOrder)
    FROM (
        SELECT 
            T.Id AS Invoice_Id, 
            T.id_client AS [Invoice.id_client], 
            T.amount AS Invoice_amount, 
            T.dateInvoice AS Invoice_dateInvoice, 
            T.idOrder AS Invoice_idOrder, 
            True AS _from0
        FROM VirtualShopModelStoreContainer.Invoices AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for VirtualShopEntities.Orders.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView3()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Orders
        [VirtualShopModel.Order](T1.Order_Id, T1.Order_units, T1.Order_idClient, T1.Order_ProductId)
    FROM (
        SELECT 
            T.Id AS Order_Id, 
            T.units AS Order_units, 
            T.idClient AS Order_idClient, 
            T.idProduct AS Order_ProductId, 
            True AS _from0
        FROM VirtualShopModelStoreContainer.Orders AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for VirtualShopModelStoreContainer.Products.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView4()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Products
        [VirtualShopModel.Store.Products](T1.Products_Id, T1.Products_price, T1.Products_units, T1.Products_image, T1.Products_description)
    FROM (
        SELECT 
            T.Id AS Products_Id, 
            T.price AS Products_price, 
            T.units AS Products_units, 
            T.image AS Products_image, 
            T.description AS Products_description, 
            True AS _from0
        FROM VirtualShopEntities.Products AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for VirtualShopModelStoreContainer.Stock.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView5()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Stock
        [VirtualShopModel.Store.Stock](T1.Stock_Id, T1.Stock_idProduct, T1.Stock_units)
    FROM (
        SELECT 
            T.Id AS Stock_Id, 
            T.idProduct AS Stock_idProduct, 
            T.units AS Stock_units, 
            True AS _from0
        FROM VirtualShopEntities.Stocks AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for VirtualShopEntities.Products.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView6()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Products
        [VirtualShopModel.Product](T1.Product_Id, T1.Product_price, T1.Product_units, T1.Product_image, T1.Product_description)
    FROM (
        SELECT 
            T.Id AS Product_Id, 
            T.price AS Product_price, 
            T.units AS Product_units, 
            T.image AS Product_image, 
            T.description AS Product_description, 
            True AS _from0
        FROM VirtualShopModelStoreContainer.Products AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for VirtualShopEntities.Stocks.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView7()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Stocks
        [VirtualShopModel.Stock](T1.Stock_Id, T1.Stock_idProduct, T1.Stock_units)
    FROM (
        SELECT 
            T.Id AS Stock_Id, 
            T.idProduct AS Stock_idProduct, 
            T.units AS Stock_units, 
            True AS _from0
        FROM VirtualShopModelStoreContainer.Stock AS T
    ) AS T1");
        }
    }
}
